#!/usr/bin/env ruby

# Handle any incoming GitHub hook

require 'jobly/boot'

commit = ENV['LOADRUNNER_COMMIT']
repo = ENV['LOADRUNNER_REPO']

# Execute a Jobly job

Build.execute_async repo: repo, commit: commit
